### PR TITLE
gh-63: Return error if other is nil

### LINKED ISSUE #63: Segfault when using non existent image
I stumbled over this, when I tried the code example and supplied a filename which didn't exist:
```go
func main() {
	if len(os.Args) < 3 {
		log.Fatalln("Usage: hash img1 img2")
	}

	log.Printf("1: %s, 2: %s\n", os.Args[1], os.Args[2])
	file1, _ := os.Open(os.Args[1])
	file2, _ := os.Open(os.Args[2])
	defer file1.Close()
	defer file2.Close()

	img1, _ := jpeg.Decode(file1)
	img2, _ := jpeg.Decode(file2)

	hash1, _ := goimagehash.DifferenceHash(img1)
	hash2, _ := goimagehash.DifferenceHash(img2)
	distance, _ := hash1.Distance(hash2)

	fmt.Printf("Distance between images: %v\n", distance)
}
```
Whenn I call this with the first or second argument given a non-existent file, the following happens:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4ab74c]

goroutine 1 [running]:
github.com/corona10/goimagehash.(*ImageHash).GetKind(...)
        /home/scip/go/pkg/mod/github.com/corona10/goimagehash@v1.1.0/imagehash.go:75
github.com/corona10/goimagehash.(*ImageHash).Distance(...)
        /home/scip/go/pkg/mod/github.com/corona10/goimagehash@v1.1.0/imagehash.go:57
main.main()
        /home/scip/dev/play/hash/main.go:28 +0x2cc
```

As you can see, there's no error checking on my side, so that's not the librarys fault. However, I think it would be better to do some additional check. There's already a nil test in DifferenceHash(), so I don't know what's going on exactly, but a viable error message would be better.

Thanks for the library anyway!

Tom

### PR DESCRIPTION
**Pull request by corona10**
closes: gh-63

### CODE REVIEW

File: imagehash_test.go [hunk 1]
```diff
@@ -56,6 +56,18 @@ func TestNewImageHash(t *testing.T) {
...
 }
 
+func TestNil(t *testing.T) {
+	hash := NewImageHash(0, AHash)
+	dis, err := hash.Distance(nil)
+	if dis != -1 {
+		t.Errorf("Distance is expected as %d but got %d", -1, dis)
+	}
+	expectedError := errors.New("other should not be nil")
+	if err != nil && err.Error() != expectedError.Error() {
```
Comment (HyeockJinKim) [inline imagehash_test.go:66]: It's a common pattern in golang to handle errors first, and it's a good idea to follow this pattern.

Comment (HyeockJinKim) [inline imagehash_test.go:66]: Rather than comparing the `Error()` string of the error value, it seems better to declare the error value as a global variable and compare it to `errors.Is` (or `==`).

Comment (corona10) [reply imagehash_test.go]: Would you like provide concrete suggestions?

File: imagehash.go [hunk 2]
```diff
@@ -54,6 +54,9 @@ func (h *ImageHash) Bits() int {
 
 // Distance method returns a distance between two hashes.
 func (h *ImageHash) Distance(other *ImageHash) (int, error) {
+	if other == nil {
+		return -1, errors.New("other should not be nil")
+	}
```
Comment (HyeockJinKim) [inline imagehash.go:59]:
```suggestion
var errNoOther = errors.New("other should not be nil")

// Distance method returns a distance between two hashes.
func (h *ImageHash) Distance(other *ImageHash) (int, error) {
	if other == nil {
		return -1, errNoOther
	}
```

This is example code, and it looks like the error global variable should be declared at the top if possible.

File: imagehash_test.go [hunk 3]
```diff
@@ -56,6 +56,18 @@ func TestNewImageHash(t *testing.T) {
...
+func TestNil(t *testing.T) {
+	hash := NewImageHash(0, AHash)
+	dis, err := hash.Distance(nil)
+	expectedError := errors.New("other should not be nil")
+	if err != nil && err.Error() != expectedError.Error() {
+		t.Errorf("Expected err %s, actual %s", expectedError, err)
+	}
+	if dis != -1 {
+		t.Errorf("Distance is expected as %d but got %d", -1, dis)
+	}
```
Comment (HyeockJinKim) [inline imagehash_test.go:68]:
```suggestion
	dis, err := hash.Distance(nil)
	if err != nil && !errors.Is(err, errNoOther) {
		t.Errorf("Expected err %s, actual %s", expectedError, err)
	}
	if dis != -1 {
		t.Errorf("Distance is expected as %d but got %d", -1, dis)
	}
```

The `err != nil` can be omitted.

Comment (corona10) [reply imagehash_test.go]: Done!

Comment (corona10) [reply imagehash_test.go]: hmm errors.Is is not supported in old golang verison

**Review by HyeockJinKim — APPROVED** [review]
LGTM!
